name: Push to GitHub pages

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Push to GitHub pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Deploy GitHub pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./dist
          CLEAN: true
